### ISSUE TITLE
Speaker routing is not working in iOS 13.6

### ISSUE THREAD

**Issue by s1Moinuddin** [AgoraIO-Usecase/Video-Calling#24]
In VideoChatViewController, Audio route is set true for Speaker. 
agoraKit.setDefaultAudioRouteToSpeakerphone(true)

But after joining channel, self.agoraKit.isSpeakerphoneEnabled() returns false. 
After joining the channel, I have set self.agoraKit.setEnableSpeakerphone(true). Still audio is not routing to speaker. 
I can hear voice in earpiece. Unable to route it to the speaker. 

Version: 'AgoraRtcEngine_iOS', '~> 3.0.1'

**Comment by plutoless** [comment]
the call is removed in https://github.com/AgoraIO-Usecase/Video-Calling/pull/25
in this use case we use callkit so we suggest to not let agora sdk handle audio routing. this is why the call failed.

**Comment by plutoless** [comment]
I'm closing this issue, feel free to open it for potential more questions.
