### ISSUE TITLE
Android SetEnableSpeakerphone not working

### ISSUE THREAD

**Issue by kushalhyperlink** [AgoraIO-Usecase/Video-Calling#30]
Hello Team 

1. Intiate the audio call
2. join the channel 
3. setDefaultAudioRoutetoSpeakerphone(true)
rtcEngine().isSpeakerphoneEnabled() is always retrun false 
4. try with rtcEngine().setEnableSpeakerphone(true)
in all above scenario could not able to enable speaker 

Please share your valuable feedback for the same

**Comment by plutoless** [comment]
@kushalhyperlink as the doc indicates, this api only works for iOS.
https://docs.agora.io/en/Video/API%20Reference/oc/Classes/AgoraRtcEngineKit.html#//api/name/setDefaultAudioRouteToSpeakerphone:
