### ISSUE TITLE
[OpenDuo-Web] Logon failure

### ISSUE THREAD

**Issue by caobaloc12** [AgoraIO-Usecase/Video-Calling#33]
I clone and start the OpenDuo-Web but encounter this error: 
`RTM:ERROR Error Code 5. The vendor enabled the dynamic key, but uses the static key`
My `.env` file already updated. 
`
REACT_APP_AGORA_APP_ID=my_app_id
REACT_APP_AGORA_APP_TOKEN=my_temp_token
REACT_APP_AGORA_LOG=true
`

**Comment by yoreland** [comment]
RTM currently don't support temp token on console.
If it is for demo purpose only. Can you just use app id without token?

**Comment by caobaloc12** [comment]
@yoreland thanks for the response. I removed the token in client login function:
```js script
//login uid
 login(uid) {
    this._uid = uid;
    return this._client.login({ uid })
      .then(() => {
        this.status = 'onLine'
     });
 }
```

now getting this error when starting a call

```
RTM:ERROR Error Code 102. The client is not logged in.
```

**Comment by caobaloc12** [comment]
Turned out the app that I created was enabled the token. I created new one without token and it worked. Close this issue.
