### ISSUE TITLE
iOS集成RTC和RTM冲突

### ISSUE THREAD

**Issue by sensencoder** [AgoraIO-Usecase/Video-Calling#8]
objc[5704]: Class AgoraReachability is implemented in both /private/var/containers/Bundle/Application/5AB3580C-9F6D-47E1-A6F2-521C26360D04/OpenDuo.app/Frameworks/AgoraRtcKit.framework/AgoraRtcKit (0x101cd9288) and /private/var/containers/Bundle/Application/5AB3580C-9F6D-47E1-A6F2-521C26360D04/OpenDuo.app/OpenDuo (0x100dd0a88). One of the two will be used. Which one is undefined.

**Comment by CavanSu** [comment]
这个不影响的，rtc 跟 rtm 里面都有实现了  AgoraReachability

**Comment by CavanSu** [comment]
这个不影响的，rtc 跟 rtm 里面都有实现了  AgoraReachability

**Comment by sensencoder** [comment]
> 这个不影响的，rtc 跟 rtm 里面都有实现了  AgoraReachability

好的谢谢，没有影响就行。
